### ISSUE TITLE
Character encoding for properties

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#20]
Looks like some properties need special character encodings:
https://github.com/fvanroie/hasp-lvgl/discussions/105
What I was trying to do:
For object:
`{"obj":"dropdown","id":4,"x":75,"y":235,"w":90,"h":30,"options":""}`
Trying to populate the `options` property programmatically with the hvac_modes of the climate:
```yaml
      - obj: "p2b4"
        properties:
          "options": >
            {% for mode in state_attr('climate.my_thermostat','hvac_modes') %}
            {{ mode }}\n{%- if not loop.last %}
            {%- endif %}
            {%- endfor %}
```

**Comment by fvanroie** [comment]
`\n` is not a special character encoding... it's just a newline character {{ 0x0d }}.

**Comment by nagyrobi** [comment]
Unfortunately they are ignored.

For example in HA's template editor this:
```
{% for mode in state_attr('climate.halo_klima','hvac_modes') %}
{{ mode }}{%- if not loop.last %}
{%- endif %}
{%- endfor %}
```
results in:
```
off
heat_cool
heat
cool
dry
fan_only
```
Containing the newlines. But on the screen it appears as:
![kép](https://user-images.githubusercontent.com/1550668/112332725-47b85300-8cba-11eb-9095-e1a0157e8eef.png)

**Comment by nagyrobi** [comment]
Also it's not possible to set any UTF-8 bytes in the Jinja2 template as that only handles ready-made strings, it's all fixed internally at UTF-8 already. That's why we get [this](https://github.com/fvanroie/hasp-lvgl/discussions/105#discussioncomment-523982).

**Comment by fvanroie** [comment]
I don't know any jinja, but did you try
```
{% for mode in state_attr('climate.halo_klima','hvac_modes') %}
{{ mode }}{{ 0x0d }}{%- if not loop.last %}
{%- endif %}
{%- endfor %}
```

**Comment by dgomes** [comment]
{% for mode in state_attr('climate.halo_klima','hvac_modes') %}
{{ mode }}{{ "\n"|e }}{%- if not loop.last %}
{%- endif %}
{%- endfor %}

**Comment by nagyrobi** [comment]
@dgomes that did it thanks.
What would be the trick to put the UTF-8 bytes in? see 3 posts above

**Comment by dgomes** [comment]
You escape the string in the template ```| e```

**Comment by nagyrobi** [comment]
Excellent, thank you!
