### ISSUE TITLE
Feature request: Friendly name

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#27]
Have a friendly name to display in Lovelace instead of the safe-only entity name name from config.

**Comment by dgomes** [comment]
went missing some commits ago, but it's back!

**Comment by nagyrobi** [comment]
Where can be set? No configurable option.

**Comment by nagyrobi** [comment]
I can set a name from Lovelace for main plate and backlight, not moodlight.
Would be better to be able to pre-set a friendly name from configuration.yaml because this way the name has to be set one by one for each sub-entity.

**Comment by dgomes** [comment]
I've started cleaning up the code to make it acceptable for HA inclusion, friendly name are no longer accepted

**Comment by dgomes** [comment]
you can now change the name of the moonlight

**Comment by nagyrobi** [comment]
> I've started cleaning up the code to make it acceptable for HA inclusion, friendly name are no longer accepted

I really don't get it why they make so many stupid constraints.

**Comment by dgomes** [comment]
it's about maintaining consistency over all the different integrations, currently that's achieved through the lovelace interface
