### ISSUE TITLE
Create backlight and moodlight dimmer

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#3]
Option to get/set the backlight level.
This could be in sync with lights in the room, day/night etc.

**Comment by fvanroie** [comment]
Check out the [backlight commands](https://fvanroie.github.io/hasp-docs/#commands/#backlight): `dim` and `light`

**Comment by nagyrobi** [comment]
Maybe as a dimmer and colorpicker for moodlight.

**Comment by dgomes** [comment]
check the new light entities

**Comment by nagyrobi** [comment]
Great!
