### ISSUE TITLE
Create touch binary sensor

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#4]
A binary sensor "Screen touched" which should change to True in the moment somebody touches the screen, and reverts to false after 1s.

Useful to automate backlight levels.

**Comment by fvanroie** [comment]
This sounds like the `idle` state that is built into hasp-lvgl. There is a `SHORT` and `LONG` interval which are configurable and the change is sent out automatically.

**Comment by dgomes** [comment]
Which command can be used to change the interval @fvanroie ?

**Comment by fvanroie** [comment]
You can change the settings with command `config/gui {"idle1":60,"idle2":120}`
These are runtime parameters that are saved at reboot only at the moment (no *save* command).
But you can change them anytime and take effect immediately.

**Comment by nagyrobi** [comment]
We can use the idle times to handle this information.
