### ISSUE TITLE
Sensor not updating "text", "value_str" property

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#7]
See this: https://github.com/fvanroie/hasp-lvgl/discussions/37#discussioncomment-433181
The sensor in the top-right corner doesn't get the update. Why?

**Comment by dgomes** [comment]
still work in progress! I only work on this on the week 😅 currently track will only change buttons "val" property

**Comment by fvanroie** [comment]
I finally managed to install HACS and the component, so I can test some things too.
I'll see if I can get the example of @nagyrobi to work here on ly Lanbon.

**Comment by nagyrobi** [comment]
I see so much potential in this! We could make it a really professional.

**Comment by nagyrobi** [comment]
Suggestion: Would be nice to have this as an option in configuration.yaml, for object, to specify which property should the updated by track. Maybe if not specified (like it is now) should go to "`val`", or optionally we could override to "`text`", "`value_str`".

Also for the track, allow specification of template containing the entity_id, something like:
`"Temp: {{states('sensor.room_temp')}}°C"`
To be able to add prefix/suffix to the value.

**Comment by nagyrobi** [comment]
Done in https://github.com/dgomes/hasp-lvgl-custom-component/commit/a1f5704fc1a71e0e6188f796e5e2b34e98c190c4 .

```
      - obj: "p0b4"
        properties:
          "text": "{{ states('sensor.mytemp') }}"
```
