### ISSUE TITLE
Implement decimal values for slider and arc (adjustable)

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#9]
Please see https://github.com/fvanroie/hasp-lvgl/issues/81

**Comment by dgomes** [comment]
this is easy to support, but lets just say that is very low in the priority list 😉

**Comment by fvanroie** [comment]
I didn't mean to thow this your way :D

**Comment by nagyrobi** [comment]
We're just collecting ideas...

**Comment by nagyrobi** [comment]
Well looks like this component has a great future: https://github.com/fvanroie/hasp-lvgl/issues/88

**Comment by nagyrobi** [comment]
Doable using templates: https://github.com/dgomes/hasp-lvgl-custom-component/pull/14#issuecomment-803646501
